[build]
dockerfilePath = "apps/api/Dockerfile"

[deploy]
region = "asia-southeast1"
startCommand = "node dist/main.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
